name: Build Linux

on:
  workflow_dispatch:
    inputs:
      commit:
        default: 'master'
        description: 'which commit should be build'
jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.inputs.commit }}

    - name: Update golang
      run: |
          sudo apt-get purge golang*
          git clone https://github.com/udhos/update-golang
          cd update-golang
          sudo ./update-golang.sh
          echo "/usr/local/go/bin:$GITHUB_PATH" > $GITHUB_PATH
          sudo rm -fr /usr/bin/go && sudo ln -s /usr/local/go/bin/go /usr/bin/
          sudo rm -fr /usr/bin/gofmt && sudo ln -s /usr/local/go/bin/gofmt /usr/bin/
          go version

    - name: Install Dependencies
      run: |
          sudo apt-get update && sudo apt-get -y install \
          btrfs-progs \
          git \
          go-md2man \
          iptables \
          libassuan-dev \
          libbtrfs-dev \
          libc6-dev \
          libdevmapper-dev \
          libglib2.0-dev \
          libgpgme-dev \
          libgpg-error-dev \
          libprotobuf-dev \
          libprotobuf-c-dev \
          libseccomp-dev \
          libselinux1-dev \
          libsystemd-dev \
          pkg-config \
          runc \
          uidmap
          
    - name: Build
      run: |
          make BUILDTAGS="seccomp"
          sudo make podman-release
          
    - uses: actions/upload-artifact@v3
      with:
        name: podman-release
        path: ./podman-*.tar.gz

    - name: 发布Release
      uses: 'marvinpinto/action-automatic-releases@latest'
      with:
        repo_token: '${{ secrets.GITHUB_TOKEN }}'
        automatic_release_tag: ${{ github.event.inputs.commit }}
        prerelease: false
        files: ./podman-*.tar.gz
    - name: 失败调试
      uses: P3TERX/ssh2actions@main
      if: ${{ failure() }}
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}        